from .speed_up import speed_up
from .slow_down import slow_down
from .midi_to_wav import midi_to_wav
from .remove_vocal import remove_vocal
from .rhymes import rhymes
from .find_key import find_key
from .find_tempo import find_tempo
from .normalize_sound import normalize_sound
from .bassboost import bassboost
